version: '3.9'


services:
  db:
    image: postgres:15
    container_name: incident_db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
  api:
    container_name: incident_api
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head
             && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
